cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    s3:
      bucket: catch-s3
    stack:
      auto: false

server:
  port: 8001
spring:
  application:
    name: thecatch
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/thecatch # basic
    username: root
    password: 1234 # 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: info
jwt:
  secretKey:
  issuer: thecatch
  access:
    expiration-minutes: 30
#    액세스 토큰의 유효 시간은 30분
  refresh:
    expiration-hours: 24
#    리프레시 토큰의 유효시간은 24시간

symmetricKey: a00aa00000aaaaaaafdfdfdf98989889 # 로컬용 운영은 다른 key 적용