
server:
  port: 8001
spring:
  application:
    name: thecatch
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/thecatch # basic
    username: root
    password: 1234 # 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update #create
    show-sql: true


  redis:
    host: localhost
    port: 6379


logging:
  level:
    root: info

