server:
  port: 8003

spring:
  application:
    name: event
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: catchevent
      auto-offset-reset: earliest
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: info
