cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    s3:
      bucket: catch-s3
    stack:
      auto: false

server:
  port: 8001
spring:
  application:
    name: thecatch
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: ${REDIS_HOST}
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_SMTP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: info
jwt:
  secretKey: ${JWT_SECRETKEY}
  issuer: thecatch
  access:
    expiration-minutes: 30
  #    액세스 토큰의 유효 시간은 30분
  refresh:
    expiration-hours: 24
#    리프레시 토큰의 유효시간은 24시간

symmetricKey: ${SYMMETRICKEY}

kafka:
  topic: "limited-coupon-apply"
  groupId: "catchevent"
